default_authorized_users:
  - root
  - jr
  - toto
  - lekiks
  - n0rk
  - david

netplan_search_domains:
  - arcticpenguin.local

AD_Base_DN: "dc=arcticpenguin,dc=local"
AD_Domain_Name: "mad01.{{ netplan_search_domains }}"