---
nextcloud_www_dir: /var/www/html
Nextcloud_Server_Name: "nextcloud.arcticpenguin.local"
SSL_Certificate_File: "nextcloud.arcticpenguin.local.crt"
SSL_CertificateKey_File: "nextcloud.arcticpenguin.local.key"

Docker_nextcloud_conf_path: "/srv/nextcloud-conf/apache/"
Docker_nextcloud_conf_http_file: "000-default.conf"
Docker_nextcloud_conf_https_file: "default-ssl.conf"
nextcloud_user: www-data
nextcloud_group: www-data



