netplan_ip: 10.0.30.2
netplan_gateway: 10.0.30.1
netplan_interface: eth0
netplan_dns:
  - 10.0.20.2
  - 10.0.20.3
  - 9.9.9.9
netplan_renderer: NetworkManager

extra_authorized_users:
 - node-exp
 - wazuh

ufw_rules:
  - port: 22
    from:
      - "10.0.30.1"     # pfsense admin interface

  - port: 9100          # node exporter
    from:
      - "10.0.20.6"     # mon01

  - port: 9256          # process exporter
    from:
      - "10.0.20.6"     # mon01
