---
- name: Create system user for node_exporter
  user:
    name: "{{ node_exporter_user }}"
    shell: /usr/sbin/nologin
    system: yes
    create_home: no

- name: Download node_exporter binary
  get_url:
    url: "https://github.com/prometheus/node_exporter/releases/download/v{{ node_exporter_version }}/node_exporter-{{ node_exporter_version }}.linux-amd64.tar.gz"
    dest: "/tmp/node_exporter.tar.gz"

- name: Extract node_exporter binary
  unarchive:
    src: "/tmp/node_exporter.tar.gz"
    dest: "/tmp"
    remote_src: yes
    extra_opts: [--strip-components=1]
    creates: "{{ node_exporter_install_dir }}/node_exporter"

- name: Copy node_exporter binary to install dir
  copy:
    src: "/tmp/node_exporter"
    dest: "{{ node_exporter_install_dir }}/node_exporter"
    owner: "{{ node_exporter_user }}"
    group: "{{ node_exporter_group }}"
    mode: '0755'
    remote_src: yes

- name: Create systemd service for node_exporter
  template:
    src: node_exporter.service.j2
    dest: /etc/systemd/system/{{ node_exporter_service_name }}.service
  notify: Reload systemd

- name: Enable and start node_exporter
  systemd:
    name: "{{ node_exporter_service_name }}"
    enabled: yes
    state: started
