- name: Set hostname
  hostname:
    name: "{{ ansible_host }}"

- name: Update /etc/hosts
  lineinfile:
    path: /etc/hosts
    line: "127.0.1.1 {{ ansible_host }}"
    regexp: '^127\.0\.1\.1'
    state: present