- hosts: all
  become: true

  roles:
    - role: host
      tags: ['common', 'hostname']
    - role: users
      tags: ['common', 'users']
    - role: ssh_hardening
      tags: ['common', 'ssh']
    - role: netplan
      tags: ['common', 'network']
    - role: ufw_firewall
      tags: ['security', 'firewall']
    - role: packages
      tags: ['common', 'packages']
    - role: node_exporter
      tags: ['monitoring']
    - role: process_exporter
      tags: ['monitoring']
