$ANSIBLE_VAULT;1.1;AES256
36346366333238356537383862303939616561646531346636333738663434383733333661353834
3130386135313862386666313361616338303937373063620a643166346563643862373434353932
31313237353636653337636262343534646666653738656434623631306233623137663436353335
6362363734653736380a643863653339343161383365323761626539653961356337376664646531
61346363616364383238373138306562363837363162653964356465396564393363376264613361
66653834653966653932313966333761303239663230623135323132323539306632643162663764
39613532363861643234636563383433326632653662303439313137653335333036393838353132
63643034653036333566393939393933313932643739313433663938613164643761636331373032
32343165656432653538343933643564636262653836303764353736663861303839336364313363
37333763373361636363356536373663376131616536353636333337343838346231383465643334
61643564633639643565616236633562373166333932323636326231343138333935653264363564
65373039366663316363616363663138303932353462336238656362396262656336633066333963
65316164653533613436616637366263333233633234323836313163303566616265373837323065
62613438386664333366623061323063313931623034316561616363373632363862646263353631
33623662366366303561323636626666326638376361386665353131623766353561336461333738
64333866653563393539
